FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration=production

FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/dist/frontend/browser /app/dist/frontend
COPY package*.json ./
COPY server.js . 
RUN npm install --omit=dev express

EXPOSE 80
CMD ["node", "server.js"]