version: '3.8'
services:
  backend:
    build: ./backend
    container_name: final-contact-manager-backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    depends_on:
      - couchdb

  frontend:
    build: ./frontend
    container_name: final-contact-manager-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  couchdb:
    image: couchdb:latest
    container_name: final-contact-manager-couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: eileen
      COUCHDB_PASSWORD: 1234567
    volumes:
      - couchdb_data:/opt/couchdb/data
  
volumes:
  couchdb_data: