version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    depends_on:
      - couchdb

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  couchdb:
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: eileen
      COUCHDB_PASSWORD: 1234567