services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always
  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: eileen
      COUCHDB_PASSWORD: 1234567
    networks:
      - app-network
    restart: always
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 5s
      retries: 5
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - COUCHDB_URL=http://eileen:1234567@couchdb:5984
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - app-network
    restart: always
  
networks:
  app-network:
    driver: bridge